version: 2

jobs:
  build_8:
    docker:
      - image: circleci/node:8
    working_directory: ~/node8
    steps:
      - checkout

      - restore_cache:
          keys:
            - 8-dep-{{ checksum "package.json" }}
            - 8-dep-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: 8-dep-{{ checksum "package.json" }}

      - run: yarn test

  build_10:
    docker:
      - image: circleci/node:10
    working_directory: ~/node10
    steps:
      - checkout

      - restore_cache:
          keys:
            - 10-dep-{{ checksum "package.json" }}
            - 10-dep-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: 10-dep-{{ checksum "package.json" }}

      - run: yarn test

  build_12:
    docker:
      - image: circleci/node:12
    working_directory: ~/node12
    steps:
      - checkout

      - restore_cache:
          keys:
            - 12-dep-{{ checksum "package.json" }}
            - 12-dep-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: 12-dep-{{ checksum "package.json" }}

      - run: yarn build

      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/deploy
    steps:
      - checkout

      - run: echo "registry=https://registry.npmjs.org/" > ~/.npmrc
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

      - run: npm publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_8:
          filters:
            tags:
              only: /^v.+/
      - build_10:
          filters:
            tags:
              only: /^v.+/
      - build_12:
          filters:
            tags:
              only: /^v.+/
      - deploy:
          requires:
            - build_8
            - build_10
            - build_12
          filters:
            tags:
              only: /^v.+/
            branches:
              ignore: /.+/
