version: 2

jobs:
  build_6:
    docker:
      - image: circleci/node:6
    working_directory: ~/node6
    steps:
      - checkout

      - restore_cache:
          keys:
          - 6-dep-{{ checksum "package.json" }}
          - 6-dep-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: 6-dep-{{ checksum "package.json" }}

      - run: yarn test

  build_8:
    docker:
      - image: circleci/node:8
    working_directory: ~/node8
    steps:
      - checkout

      - restore_cache:
          keys:
          - 8-dep-{{ checksum "package.json" }}
          - 8-dep-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: 8-dep-{{ checksum "package.json" }}

      - run: yarn test

  build_10:
    docker:
      - image: circleci/node:10
    working_directory: ~/node10
    steps:
      - checkout

      - restore_cache:
          keys:
          - 10-dep-{{ checksum "package.json" }}
          - 10-dep-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: 10-dep-{{ checksum "package.json" }}

      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/deploy
    steps:
      - checkout

      - run: echo "registry=https://registry.npmjs.org/" > ~/.npmrc
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

      - run: npm publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_6
      - build_8
      - build_10
      - deploy:
          requires:
            - build_6
            - build_8
            - build_10
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]+(\.[0-9]+)*/