version: 2

jobs:
  build_12:
    docker:
      - image: circleci/node:12
    working_directory: ~/node12
    steps:
      - checkout

      - restore_cache:
          keys:
            - 12-dep-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: 12-dep-{{ checksum "package.json" }}

      - run: yarn build

      - run: yarn test

  build_14:
    docker:
      - image: circleci/node:14
    working_directory: ~/node14
    steps:
      - checkout

      - restore_cache:
          keys:
            - 14-dep-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: 14-dep-{{ checksum "package.json" }}

      - run: yarn build

      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:14
    working_directory: ~/deploy
    steps:
      - checkout

      - run: echo "registry=https://registry.npmjs.org/" > ~/.npmrc
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

      - run: npm publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_12:
          filters:
            tags:
              only: /^v.+/
      - build_14:
          filters:
            tags:
              only: /^v.+/
      - deploy:
          requires:
            - build_12
            - build_14
          filters:
            tags:
              only: /^v.+/
            branches:
              ignore: /.+/
